/* Generate with the unchanged paper reference only. */
#include "vendor/chainhash_ref.h"
#include <cstdio>
#include <vector>
int main() {
    std::vector<uint8_t> data(262144);
    for(size_t i=0;i<data.size();++i) data[i]=(uint8_t)(i*131+17);
    std::puts("/* Generated by test/generate_vectors.cpp; data[i]=(131*i+17) mod 256. */\nstruct test_vector { uint64_t seed; size_t len; uint64_t hash; };\nstatic const test_vector vectors[] = {");
    for(uint64_t seed: {UINT64_C(0),UINT64_C(1),UINT64_C(0xffffffffffffffff),UINT64_C(0x0123456789abcdef)}) {
        auto k=chainhash_ref::Key<>::from_seed(seed);
        for(size_t n: {size_t(0),size_t(1),size_t(7),size_t(8),size_t(9),size_t(15),size_t(16),size_t(17),size_t(31),size_t(32),size_t(33),size_t(63),size_t(64),size_t(65),size_t(255),size_t(256),size_t(257),size_t(511),size_t(512),size_t(513),size_t(1024),size_t(4096),size_t(262144)})
            std::printf("    {UINT64_C(0x%016llx), %zu, UINT64_C(0x%016llx)},\n",(unsigned long long)seed,n,(unsigned long long)chainhash_ref::hash(k,data.data(),n));
    }
    std::puts("};");
}
