#!/usr/bin/env python3
"""Generate an explicit axiom audit and verbatim theorem signature catalogue."""
from pathlib import Path
import re
root = Path(__file__).resolve().parent

def strip_comments(s):
    # Keep offsets/newlines, including nested Lean block comments.
    out = list(s); i = 0; depth = 0
    while i < len(s):
        if s.startswith('/-', i): depth += 1; out[i:i+2] = '  '; i += 2
        elif depth and s.startswith('-/', i): depth -= 1; out[i:i+2] = '  '; i += 2
        elif depth:
            if s[i] != '\n': out[i] = ' '
            i += 1
        elif s.startswith('--', i):
            j = s.find('\n', i)
            if j < 0: j = len(s)
            out[i:j] = ' ' * (j-i); i = j
        else: i += 1
    return ''.join(out)

names = []; catalogue = []
for p in sorted((root/'ProvenHashes').glob('*.lean')):
    raw = p.read_text(); clean = strip_comments(raw); stack = []
    entries = []
    for m in re.finditer(r'(?m)^\s*(?:(namespace)\s+(\S+)|(section)(?:\s+(\w+))?\s*$|(end)(?:\s+(\S+))?\s*$|((?:@\[[^\n]*\]\s*)?)(?:(private)\s+)?(theorem|lemma)\s+(\S+))',clean):
        if m[1]: stack.append(m[2])
        elif m[3]: stack.append('')
        elif m[5]:
            if stack: stack.pop()
        elif not m[8]:
            name = '.'.join([s for s in stack if s]+[m[10]])
            start = clean.find(m[9]+' '+m[10], m.start())
            stop = clean.find(':=', start)
            if stop < 0: raise ValueError((p,name))
            signature = raw[start:stop].rstrip()
            names.append(name); entries.append((name,signature))
    catalogue.append((p.name,entries))
assert len(set(names)) == len(names), 'Duplicate declarations'
(root/'Verification.lean').write_text('import ChainHash\n\n-- Generated by generate_verification.py; every public theorem/lemma.\n'+''.join('#print axioms '+n+'\n' for n in names))
with (root/'THEOREM_STATEMENTS.md').open('w') as f:
    f.write('# Exported theorem statements\n\nVerbatim source signatures; namespace and source are given for each.\nVariables declared at module/section scope remain implicit here; see the linked module for their context.\n\n')
    for module,entries in catalogue:
        f.write('## ['+module+'](ProvenHashes/'+module+')\n\n')
        for name,sig in entries: f.write('`'+name+'`\n\n```lean\n'+sig+'\n```\n\n')
print(f'{len(names)} exported theorem/lemma declarations')
